name: kivicare_flutter
description: A new Flutter application.

publish_to: "none"

version: 0.0.3+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase for crashlytics

  firebase_crashlytics: ^3.4.5
  firebase_analytics: ^10.7.1

  firebase_remote_config: ^4.3.5
  google_fonts: ^6.1.0
  moment_dart: ^1.1.0

  #State Management Technique
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0

  nb_utils: ^6.0.7
  scan: ^1.6.0

  #API calling
  http: ^1.1.0
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-alpha.6
  intl: ^0.18.1

  # Images and Icons
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  cached_network_image: ^3.3.0
  webview_flutter: ^4.4.2
  flutter_slidable: ^3.0.1
  percent_indicator: ^4.2.3
  signature: ^5.4.1
  path_provider: ^2.1.1
  photo_view: ^0.14.0
  # bar chart
  fl_chart: ^0.66.0

  #APP Information
  url_launcher: ^6.2.1
  share: ^2.0.4
  flutter_custom_tabs: ^1.2.1
  get_storage: ^2.1.1

  # Pickers for image and file and dates
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  open_file: ^3.3.2
  syncfusion_flutter_datepicker: ^24.1.45
  lottie: ^3.0.0

  #OnsSignal
  onesignal_flutter: ^5.0.4

  #PAYMENT
  razorpay_flutter: ^1.3.5
  flutter_stripe: ^10.0.0

  flutter_localizations:
    sdk: flutter
  workmanager: ^0.5.2
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.13.1"
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  http: ^0.13.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/appIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/appIcon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/appIcon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/appIcon.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/doctorAvatars/
    - images/services_icon/
    - images/patientAvatars/
    - images/flags/

https://gitlab:
  com/gmits_mobile/service-provider-app/provider_flutter:
    git:
