name: momona_healthcare
description: Bringing Healthcare To Homes.

publish_to: 'none'

version: 8.7.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase for crashlytics
  firebase_crashlytics: ^3.4.8
  firebase_analytics: ^10.7.4

  firebase_remote_config: ^4.3.8
  # google_fonts: ^6.1.0
  google_fonts: ^5.1.0
  moment_dart: ^1.1.0

  #State Management Technique
  mobx: ^2.2.3
  flutter_mobx: ^2.2.0

  nb_utils: ^6.1.0
  scan: ^1.6.0

  #API calling
  http: ^1.1.0
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-alpha.6
  intl: ^0.18.1

  # Images and Icons
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  cached_network_image: ^3.3.0
  webview_flutter: ^4.4.2
  flutter_slidable: ^3.0.1
  percent_indicator: ^4.2.3
  signature: ^5.4.1
  path_provider: ^2.1.1
  photo_view: ^0.14.0
  # bar chart
  fl_chart: ^0.65.0

  #APP Information
  url_launcher: ^6.2.2
  share: ^2.0.4
  flutter_custom_tabs: ^1.2.1
  get_storage: ^2.1.1

  # Pickers for image and file and dates
  file_picker: ^6.1.1
  image_picker: ^1.0.5
  open_file: ^3.3.2
  syncfusion_flutter_datepicker: ^23.2.7
  lottie: ^2.7.0

  #OnsSignal
  onesignal_flutter: ^5.0.4

  #PAYMENT
  razorpay_flutter: ^1.3.5
  flutter_stripe: ^9.6.0

  # MAP
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  flutter_localizations:
    sdk: flutter
  #appwrite: ^12.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.7

  #flutter packages pub run build_runner build --delete-conflicting-outputs




flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/flags/
    - images/filesFormat/

https://gitlab:
  com/gmits_mobile/service-provider-app/provider_flutter:
    git: