name: kivicare_flutter
description: A new Flutter application.

publish_to: 'none'

version: 6.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # Firebase for crashlytics and googlesign in for calender
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.9.0
  firebase_analytics: ^9.3.8
  firebase_auth: ^3.11.2
  google_sign_in: ^5.4.3
  cloud_firestore: ^3.5.1
  firebase_remote_config: ^2.0.20
  google_fonts: ^3.0.1

  #State Management Technique
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5

  nb_utils: ^4.6.25
  scan: ^1.6.0

  #API calling
  http: ^0.13.5
  html: ^0.15.0
  flutter_html: ^3.0.0-alpha.6
  intl: ^0.17.0

  # Images and Icons
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  cached_network_image: ^3.2.3
  lottie: ^2.2.0
  webview_flutter: ^3.0.4
  flutter_slidable: 2.0.0
  percent_indicator: 4.2.2

  # bar chart
  fl_chart: ^0.55.2

  #APP Information
  url_launcher: ^6.1.7
  share: ^2.0.4
  flutter_custom_tabs: ^1.0.4

  # Pickers for image and file
  image_picker: ^0.8.6
  file_picker: ^4.6.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/doctorAvatars/
    - images/services_icon/
    - images/patientAvatars/
    - images/flags/

