version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30-node

    steps:
      - checkout

      - run:
          name: Setup Flutter
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              lib32stdc++6 \
              libstdc++6 \
              libglu1-mesa

            git clone -b stable https://github.com/flutter/flutter.git $HOME/flutter
            export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
            flutter doctor

            # Install Google Cloud SDK without adding the repository
            curl https://sdk.cloud.google.com | bash
            exec -l $SHELL
            gcloud components install kubectl

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pubspec.yaml" }}

      - run:
          name: Install dependencies
          command: flutter pub get

      - save_cache:
          key: v1-dependencies-{{ checksum "pubspec.yaml" }}
          paths:
            - .pub-cache

      - run:
          name: Run tests
          command: flutter test

      - run:
          name: Build APK
          command: flutter build apk

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: /artifacts

workflows:
  version: 2
  build:
    jobs:
      - build
