version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30-node

    steps:
      - checkout

      - run:
          name: Setup Flutter
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              lib32stdc++6 \
              libstdc++6 \
              libglu1-mesa

            git clone -b stable https://github.com/flutter/flutter.git $HOME/flutter
            export PATH=$HOME/flutter/bin:$HOME/flutter/bin/cache/dart-sdk/bin:$PATH
            flutter doctor

            # Add GPG key for Google Cloud SDK
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

            # Add Google Cloud SDK repository
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

            sudo apt-get update
            sudo apt-get install google-cloud-sdk

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pubspec.yaml" }}

      - run:
          name: Install dependencies
          command: flutter pub get

      - save_cache:
          key: v1-dependencies-{{ checksum "pubspec.yaml" }}
          paths:
            - .pub-cache

      - run:
          name: Run tests
          command: flutter test

      - run:
          name: Build APK
          command: flutter build apk

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: /artifacts

workflows:
  version: 2
  build:
    jobs:
      - build
