version: 2.1

orbs:
  android: circleci/android@2.4.0
  flutter: circleci/flutter@2.0.2

workflows:
  
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

jobs:
  build:
    docker:
      - image: circleci/android:api-30-node  # Use Docker executor instead of android/android-machine
    
    steps:
      - checkout

      - flutter/install_sdk: 
          version: 3.16.8

      - flutter/install_pub:
          cache-version: v1

      - run:
          name: Add Google services to App
          command: |
            echo "$GOOGLE_SERVICES" | base64 --decode > android/app/google-services.json

      - run:
          name: Flutter pub get
          command: |
            flutter pub get

      - run:
          name: Build APK
          command: |
            flutter build apk

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
